---
# Cache gems in between builds
cache:
  paths:
    - vendor/ruby

lint:rubocop:
  image: ghcr.io/ruby/ruby
  script:
    - gem install rubocop -N
    - rubocop lib

test:unit:
  before_script:
    - sed -e 's/# gem /gem /' -i Gemfile
    - gem install bundler -N
    - bundle install -j $(nproc) --path vendor
  coverage: '/\((\d+(?:.\d+)?)\%\) covered/'
  image: ghcr.io/ruby/ruby:$RUBY
  script:
    - GENERATE_REPORTS=true CI_REPORTS=reports bundle exec rake test
  parallel:
    matrix:
      - RUBY:
          - 3.0
          - 3.1
          - 3.2
  artifacts:
    expire_in: 1 week
    paths:
      - coverage/
    reports:
      junit: "reports/TEST-*.xml"

pages:
  image: ghcr.io/ruby/ruby
  stage: deploy
  needs: []
  script:
    - gem install yard -N
    - yard doc -o public/
  artifacts:
    paths:
      - public/
  only:
    - master
  when: always
