AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - '*.spec'
    - 'Rakefile'

# Broken in CI
Lint/Void:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

# Don't enforce documentation
Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Max: 50

Metrics/MethodLength:
  Max: 70

# Matrix has a lot of methods in the CS API
Metrics/ModuleLength:
  Max: 500

Metrics/LineLength:
  Max: 190

Style/RescueModifier:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Layout/RescueEnsureAlignment:
  Enabled: false
