---
sudo: false
language: ruby
rvm:
  - 2.4
  - 2.6
  - 2.7

cache:
  bundler: true
before_install:
  - gem install bundler
  - gem update --system
script:
  - bundle exec rake test
  - bundle exec rubocop
