---
name: Build container images

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build image metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ananace/matrix-sdk-bot
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/master' }}
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ananace
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.bot
          push: true
          tags: "${{ steps.meta.outputs.tags }}"
          labels: "${{ steps.meta.outputs.labels }}"
